In [1]:
import numpy as np

In [2]:
def transposed_convolution(input_matrix, kernel, stride=1, crop=0):
    
    H, W = input_matrix.shape
    kH, kW = kernel.shape
    sH, sW = stride, stride  

    H_out = sH * (H - 1) + kH
    W_out = sW * (W - 1) + kW

    output_matrix = np.zeros((H_out, W_out))

    for i in range(H):
        for j in range(W):
            output_matrix[i * sH : i * sH + kH, j * sW : j * sW + kW] += (
                input_matrix[i, j] * kernel
            )

    if crop > 0:
        output_matrix = output_matrix[crop:-crop, crop:-crop]

    return output_matrix

In [3]:
input_matrix = np.array([[2, 3], [-2, 1]])  
kernel = np.array([[2, 1, 4], [-1, -2, -3], [-2, 1, 4]]) 
stride = 3
crop = 1

In [4]:
output = transposed_convolution(input_matrix, kernel, stride, crop)
print("Output Matrix:")
print(output)

Output Matrix:
[[-4. -6. -3. -6.]
 [ 2.  8. -6.  3.]
 [-2. -8.  2.  1.]
 [ 4.  6. -1. -2.]]
